/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash.set;

import hash.set.SimpleHashSet;
import org.junit.Assert;
import org.junit.Test;

public class SimpleHashSetTests {

    @Test
    public void testAddAndContains() {
        SimpleHashSet set = new SimpleHashSet(10);
        set.add(1);
        set.add(2);

        Assert.assertTrue(set.contains(1));
        Assert.assertTrue(set.contains(2));

        Assert.assertFalse(set.contains(3));
    }

    @Test
    public void testRemove() {
        SimpleHashSet set = new SimpleHashSet(10);
        set.add(1);

        Assert.assertTrue(set.contains(1));

        set.remove(1);
        Assert.assertFalse(set.contains(1));
    }

    //
    // Tests that show why this Set isn't the best
    //

    @Test(expected = IllegalArgumentException.class)
    public void testSetFailsOnNegativeNumbers() {
        SimpleHashSet set = new SimpleHashSet(10);
        set.add(-1);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetFailsOnNumbersGreaterThanMax() {
        SimpleHashSet set = new SimpleHashSet(10);
        set.add(11);
    }
}
